repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.9"
    hooks:
      - id: ruff
        args: [--line-length=120, --ignore=F403, --ignore=PLR0913]
        stages: [pre-commit]

  - repo: https://github.com/econchick/interrogate
    rev: "1.7.0"
    hooks:
      - id: interrogate
        args: [--fail-under=45, --ignore-init-module, --ignore-init-method]
        pass_filenames: false


default_language_version:
  python: python3.11

# Exclude specific files or directories from hooks if needed
exclude: |
  ^tests/.*$  # Exclude the tests directory
  ^docs/.*$   # Exclude the docs directory    